const express = require("express");
const router = express.Router();

const { protect } = require("../middleware/authMiddleware");
const { authorizeRoles } = require("../middleware/roleMiddleware");
const { authorizeModule } = require("../middleware/moduleMiddleware");
const dashboard = require("../controllers/Accounts/dashboardController");
const transactions = require("../controllers/Accounts/transactionController");
const invoices = require("../controllers/Accounts/invoiceController");
const receipts = require("../controllers/Accounts/receiptController");
const payments = require("../controllers/Accounts/paymentController");
const expenses = require("../controllers/Accounts/expenseController");
const ledger = require("../controllers/Accounts/ledgerController");
const dayBook = require("../controllers/Accounts/dayBookController");
const taxReports = require("../controllers/Accounts/taxReportController");
const financialReports = require("../controllers/Accounts/financialReportController");
const advanceDeposits = require("../controllers/Accounts/advanceDepositController");
const refunds = require("../controllers/Accounts/refundController");
const companyBilling = require("../controllers/Accounts/companyBillingController");
const serviceTransactions = require("../controllers/Accounts/serviceTransactionController");
const journalEntries = require("../controllers/Accounts/journalEntryController");
const financialYears = require("../controllers/Accounts/financialYearController");
const auditLogs = require("../controllers/Accounts/auditLogController");
const settings = require("../controllers/Accounts/settingsController");

router.use(protect, authorizeRoles("hoteladmin", "staff", "superadmin"), authorizeModule("accounts"));

router.get("/dashboard", dashboard.dashboard);
router.get("/transactions", transactions.listTransactions);
router.post("/transactions", transactions.createTransaction);
router.get("/invoices", invoices.listInvoices);
router.post("/invoices", invoices.createInvoice);
router.get("/invoices/:invoiceId", invoices.getInvoice);
router.patch("/invoices/:invoiceId", invoices.updateInvoice);
router.post("/invoices/:invoiceId/send", invoices.sendInvoice);
router.post("/invoices/:invoiceId/payments", receipts.collectInvoicePayment);
router.get("/receipts", receipts.listReceipts);
router.post("/receipts", receipts.createReceipt);
router.get("/payments", payments.listPayments);
router.post("/payments", payments.createPayment);
router.get("/expenses", expenses.listExpenses);
router.post("/expenses", expenses.createExpense);
router.get("/ledger/chart-of-accounts", ledger.chartOfAccounts);
router.get("/ledger/:accountId/entries", ledger.ledgerEntries);
router.get("/day-book", dayBook.dayBook);
router.get("/tax-reports/gst", taxReports.gstReport);
router.get("/tax-reports/tds", taxReports.tdsReport);
router.get("/reports/profit-loss", financialReports.profitLoss);
router.get("/reports/balance-sheet", financialReports.balanceSheet);
router.get("/advance-deposits", advanceDeposits.listAdvanceDeposits);
router.post("/advance-deposits", advanceDeposits.createAdvanceDeposit);
router.get("/refunds", refunds.listRefunds);
router.post("/refunds", refunds.createRefund);
router.get("/company-billing", companyBilling.listCompanyBilling);
router.post("/company-billing", companyBilling.createCompanyBilling);
router.get("/service-transactions", serviceTransactions.listServiceTransactions);
router.get("/journal-entries", journalEntries.listJournalEntries);
router.post("/journal-entries", journalEntries.createJournalEntry);
router.get("/financial-years", financialYears.listFinancialYears);
router.post("/financial-years", financialYears.createFinancialYear);
router.patch("/financial-years/:id", financialYears.updateFinancialYear);
router.get("/audit-logs", auditLogs.auditLogs);
router.get("/settings", settings.getSettings);
router.put("/settings", settings.updateSettings);
router.get("/settings/tax", settings.getSettings);
router.put("/settings/tax", settings.updateSettings);
router.get("/settings/payment-methods", settings.getSettings);
router.put("/settings/payment-methods", settings.updateSettings);
router.get("/settings/expense-categories", settings.getSettings);
router.put("/settings/expense-categories", settings.updateSettings);

module.exports = router;
